[package]
name = "nu_plugin_highlight"
version = "0.1.0-wip"
authors = ["Tim 'Piepmatz' Hesse"]
edition = "2021"
repository = "https://github.com/cptpiepmatz/nu-plugin-highlight"
description = "A nushell plugin for syntax highlighting"
license = "MIT"

[dependencies]
# nu
nu-plugin = "0.82"
nu-protocol = "0.82"

# highlighting
syntect = "5"
nu-ansi-term = "0.48"
ansi_colours = "1"
bat = "0.23"
